image: gitpod/workspace-dotnet

tasks:
    - name: Frontend
      init: |
          cd Web
          npm ci
          npm run build:dev
      command: |
          cd Web
          npm run watch && gp sync-done frontend

    - name: Backend
      init: |
          dotnet tool restore
          dotnet paket restore
      command: |
          cd Web
          gp sync-await frontend
          dotnet watch run && gp url 5000
      openMode: split-right

ports:
    - port: 5000
      onOpen: open-browser
      visibility: public
