image: gitpod/workspace-dotnet

tasks:
    - name: Frontend
      init: |
          cd Web
          npm ci
      command: |
          cd Web
          npm run build:dev
          gp sync-done frontend
          npm run watch

    - name: Backend
      init: |
          dotnet tool restore
          dotnet paket restore
      command: |
          cd Web
          gp sync-await frontend
          gp url 5000
          dotnet watch run
      openMode: split-right

ports:
    - port: 5000
      onOpen: open-browser
      visibility: public
